spring.application.name=Trabajo-4
server.port=8106


# MongoDB Atlas URI
spring.mongodb.uri=mongodb+srv://mmiguelr1256:MarcoPolo69%40@main.drwjqup.mongodb.net/futbol_db?retryWrites=true&w=majority
spring.data.mongodb.uri=mongodb+srv://mmiguelr1256:MarcoPolo69%40@main.drwjqup.mongodb.net/futbol_db?retryWrites=true&w=majority
